In [1]:
import tensorflow as tf

In [2]:
x = tf.constant([i for i in range(12)], shape=(2, 2, 3))

In [6]:
tf.expand_dims(x, 3).shape

TensorShape([2, 2, 3, 1])

In [8]:
x[:, 1, ...]

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[ 6,  7,  8],
        [ 9, 10, 11]]])>

In [6]:
tf.math.argmax(x, 1)

<tf.Tensor: shape=(1, 2, 3), dtype=int64, numpy=
array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int64)>

In [2]:
x = tf.constant([1,2,3], dtype='int32')
y = 0.9