In [1]:
import tensorflow as tf

In [23]:
x = tf.Variable(tf.constant([1,2], shape = [1,2], dtype = 'float32'))

In [24]:
d = tf.keras.layers.Dense(1, activation='softplus', kernel_initializer=tf.keras.initializers.Ones())

In [25]:
with tf.GradientTape() as tape:
    z = d(x)

print(z)
print('---'*10)
tape.gradient(z, d.trainable_weights)

tf.Tensor([[3.0485873]], shape=(1, 1), dtype=float32)
------------------------------


[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[0.95257413],
        [1.9051483 ]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.95257413], dtype=float32)>]